color: null
fieldLayouts:
  54523156-390d-44ca-b053-c979ef56bab4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9b253881-2403-4b1a-a587-eb6d898e983b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3a11124-b86f-4a5c-9dba-5b7dbf7f1496
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f141443-d73e-4cd5-9414-23f192babda8 # Navigatie link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49f16448-6888-4092-922f-a10dc679cce8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 18fd28a1-95c7-4d85-932d-c13161d43d8e
        userCondition: null
handle: brevetten
hasTitleField: true
icon: seal
name: Brevetten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
