color: null
fieldLayouts:
  fb4a1a9d-09ef-42f4-acf2-09ee4aa75f9d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: da9c8886-186b-4609-85e5-abda78fac5be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea72abe5-bea8-4ae7-9a59-db81d2b10f9a # Titel h1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2614ea10-0052-48b8-bc1e-41b2855bd6dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02450193-808b-42e8-b4cd-9a0991eb8258 # Titel H2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 687cf7d1-e822-4e25-8f30-60d3df215872
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # uitgebreide tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8740e598-d937-4bcb-8e37-6cc722134b31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 579560c5-3e5d-4d86-b10a-5080ba6e513d # E-mail
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92910ca2-cb08-4218-9033-3d19cd4ea72a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c631f85-d835-420c-bb78-46108ffa1d43 # Google Maps link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49d1dd1b-3d5c-48a7-b0de-4a8eb95b9587
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 533ddc9a-e68e-46a9-b4d4-2aa91ba039dd
        userCondition: null
handle: contact
hasTitleField: true
icon: ''
name: contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
