color: null
fieldLayouts:
  ca8e7a33-0314-471e-88da-4c36d2c8a997:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf88517f-c9ff-4d37-b0b0-45da79ecb341
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b697bce0-480b-4ea7-8a6f-6cf6782970d1 # Privacy policy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e262022c-74ad-4e07-9778-263b2c4adb90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2977cff4-bcbc-4a4f-a18c-5e5debe273f1 # algemene voorwaarden
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62ce7bb0-3908-4220-be3b-d18dc761cfac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 950a9039-871a-447e-8e8b-6c305728b9ba # reglement
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 804de983-4337-4463-a1ca-133dfeb87c06
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 112f392c-1c71-4325-b051-dfe1ca3e7004
        userCondition: null
handle: documentenWetgeving
hasTitleField: true
icon: ''
name: 'Documenten wetgeving'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
