color: null
fieldLayouts:
  bc67a727-8f72-4808-a019-2b675412ae37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4d64547-ff14-4e08-bf25-474849143a2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # uitgebreide tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fbc1d8a-963d-42a2-a407-a188cbbc6e20
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bf5d9fb-121d-45f8-91b9-e292c5367918
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d14165d3-34b7-4d7d-992d-2468b9a0c199
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf8f250d-e4d1-4d7d-9b2d-7715bf489fc9 # Foto 3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf73e7db-4dab-4a6d-bbe6-c7c117a117ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 047f311b-5a9b-4f2a-83e5-bb93db79c152 # Foto 4
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7331b40-a2ec-4fe7-8048-461e682a1a81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 532c63e0-e8c9-43e6-a365-064f3559f2c4 # Foto 5
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17ebdae6-9560-4e83-b852-584c533254ac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82b28e9f-3f50-4ca2-8426-38186d097e28
        userCondition: null
handle: duikplaatsenIndiv
hasTitleField: true
icon: map-pin
name: Duikplaatsen-indiv
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
