color: null
fieldLayouts:
  04991244-d508-4a62-9b41-67c67b7a72d0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d21a12f1-32bf-480f-bc88-0eb3a758d77d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea72abe5-bea8-4ae7-9a59-db81d2b10f9a # Titel h1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7538bab-85e1-41d0-a1e5-122140646269
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # uitgebreide tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b1b0ef9-4261-4fe6-ad78-fdb7af05752f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34b7a798-ceef-4b73-b5ca-5d0d989e5e65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccc25683-1284-4a99-ab38-8137c359b8b3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02450193-808b-42e8-b4cd-9a0991eb8258 # Titel H2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e275e3d7-d8d9-48c9-8619-e86894523799
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6e5f486b-f97e-4b24-a0a5-b0e06ae0d0ef # duiken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 169cfd50-d6a7-4881-b32c-f8f985d3f55d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52e3e821-f939-4b6d-98e9-0da74c9d1d4c
        userCondition: null
handle: duiken
hasTitleField: true
icon: page
name: Duiken
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
