color: null
fieldLayouts:
  ec4fdace-426d-4b6f-8275-d4dd2794cca1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 37c7b861-4ed4-49a6-8fa6-f44421e24c50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea72abe5-bea8-4ae7-9a59-db81d2b10f9a # Titel h1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0249a27-683d-4f48-8104-f65696d4d10a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1445446-f351-4d73-a05f-2e88f2488769
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b50fbbe1-e8fc-4dd0-989e-f464bba4e4d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # uitgebreide tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37445e1b-1a71-4fe6-a218-835632f3e1f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ca1ff32-7d0c-4274-aeb0-2dbfb42fc6fe # Titel federaties
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 013c7531-4f6b-491b-b9c6-77ff0dd56eee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1df7427a-81f9-4008-9eb8-40f8c65bb780
        userCondition: null
handle: duiksport
hasTitleField: true
icon: memo
name: Duiksport
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
