color: null
fieldLayouts:
  66cb88f3-878f-416e-8e29-7b02b81fe1c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 69905e39-6287-4302-933b-f07e501667f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12b7a069-0112-452b-ae5f-804c0ab2992d # Uitleg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d1aeb7a-a89a-4037-9730-641294828fb8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02450193-808b-42e8-b4cd-9a0991eb8258 # Titel H2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c284d3d5-c94c-4bba-9882-412464f921aa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f141443-d73e-4cd5-9414-23f192babda8 # Navigatie link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 521530ae-8d23-4505-9048-8bb6ce7736e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1944228b-667b-4679-a9a7-5cd61ba6363b # Titel H2.2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76015f01-1fe4-4d66-aab9-ebb1e76670b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 39b5853e-79de-4dd0-be0f-e3402a38417a # Navigatie link 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 467acfc9-3b3e-4e91-8028-557cc79bf2f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d1070e7-0af4-4cdd-85d3-91155db1b7f5 # Titel H2.3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fae7794-5a77-4c16-8f2a-e01e9eecb39f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b657c4d7-f8d5-4cb8-b322-3707bfe16ed3 # Navigatie link 3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea1985bc-d8f6-4e52-9bee-3060da0dee0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8f3f5b59-9565-4841-b02f-bf67d0d6591c
        userCondition: null
handle: footerFederaties
hasTitleField: true
icon: ''
name: footer-federaties
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
