color: null
fieldLayouts:
  43464692-ef08-45dd-9e20-6b96147ea493:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5fbf6707-24bd-4210-a611-49239dce10e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5cdff2ca-dd92-4449-a912-ba044ad5f2eb
        userCondition: null
handle: kalender
hasTitleField: true
icon: ''
name: kalender
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
