color: null
fieldLayouts:
  85ef9a0e-efeb-429a-b73b-371de33bde77:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e9af1360-f614-4142-8d86-c90f3ef09fce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79fdde2b-1d39-4c09-bc32-33382b55dd9f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d1b8e8c-f843-4846-884d-d62c4d69ebc3 # Knop
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c62ca44-a96c-409c-bb6d-b179187d168f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 265af883-03ec-48d9-ae2c-4110f81fb38e
            userCondition: null
          -
            elementCondition: null
            fieldUid: 02450193-808b-42e8-b4cd-9a0991eb8258 # Titel H2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 287ce321-a5fc-417a-a2aa-bfa2f10e0536
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 89df1765-027e-45a7-b3fe-a0319b5a0a62
            userCondition: null
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8e0252d-d3e1-4212-b1ed-32a82af8c109
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf8f250d-e4d1-4d7d-9b2d-7715bf489fc9 # Foto 3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a01a8d1-577f-433d-8a04-8a702ddfc924
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1944228b-667b-4679-a9a7-5cd61ba6363b # Titel H2.2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f433b579-e141-49de-8d9f-40d82937ff13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 598e54d4-f8b0-40be-9425-bcbef9862fbf
            userCondition: null
          -
            elementCondition: null
            fieldUid: 4d1070e7-0af4-4cdd-85d3-91155db1b7f5 # Titel H2.3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae35cfbe-a9ce-4917-8d59-4eac8e82fcc0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 047f311b-5a9b-4f2a-83e5-bb93db79c152 # Foto 4
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc7f12b5-6475-4444-8f0c-c919dd22e669
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 605cd42c-5fce-4b4c-b7d4-5f1d5648d615
        userCondition: null
handle: leden
hasTitleField: true
icon: ''
name: Leden
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
