color: null
fieldLayouts:
  f6b4a98d-09ef-4158-8cf4-31b7fbd90023:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 50ba1892-16bc-45bd-aa11-8f9ee522aacc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # uitgebreide tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06d520ac-ea02-4177-9a52-d5e12f80b4d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d1b8e8c-f843-4846-884d-d62c4d69ebc3 # Knop
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ba7156d-e17d-40a9-82a8-9e3d1dd66689
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a8ddc64-ebb3-4a04-bac3-01b46f3fbf0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cdfca70-1c99-46f6-b3fe-c8c86dbca65c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 249fec65-7b63-4d51-a914-b0fc45d9ec6f
        userCondition: null
handle: met2Fotos
hasTitleField: true
icon: ''
name: 'met 2 foto''s'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
