color: null
fieldLayouts:
  0e5fd78a-befa-42c8-b017-f3ce585edc96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 728294f9-eaa4-42b5-986a-e3f76df785ff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # uitgebreide tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57ecd348-46e8-4074-8e13-65fb357a1c7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d1b8e8c-f843-4846-884d-d62c4d69ebc3 # Knop
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02cbf6b0-1a40-46b8-a5c1-3b847d44e9cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b873fe7-4c12-42f7-bed9-8d23e75bbd39
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b50ddf2-4b7d-4d66-8d68-3e3b087047b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf8f250d-e4d1-4d7d-9b2d-7715bf489fc9 # Foto 3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 200e25a5-6aa8-4cab-97cf-f4d7879946ce
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eaa4ce31-cadd-4c6e-9af9-94ebf6ac597b
        userCondition: null
handle: met3Fotos
hasTitleField: true
icon: ''
name: 'met 3 foto''s'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
