color: lime
fieldLayouts:
  f35bc253-7917-4626-b20c-835b36d79a33:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46acfc05-3626-45a8-8f9b-0ef50d105fa2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f141443-d73e-4cd5-9414-23f192babda8 # Navigatie link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc1e92b5-b26b-46a2-a471-887533f04241
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f141443-d73e-4cd5-9414-23f192babda8 # Navigatie link
            handle: navigatieLink2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ee3f4e3-36d8-49c8-8e7c-1814eda6f101
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f141443-d73e-4cd5-9414-23f192babda8 # Navigatie link
            handle: navigatieLink3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd8b6f79-fa85-44b4-806a-6732e3579401
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f141443-d73e-4cd5-9414-23f192babda8 # Navigatie link
            handle: navigatieLink4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ae33b53-2bbb-485e-842c-c524a4c8361b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b5695bff-d117-4c6c-a31d-261116a71af5
        userCondition: null
handle: navNietIngelogd
hasTitleField: false
icon: bars
name: 'Nav niet ingelogd'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
