color: null
fieldLayouts:
  994caf48-ae0d-46d4-9309-f252359a18e8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9d1f9a7a-7ef7-40cb-b015-585ddd5fba53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 988b79d3-938b-47c2-820a-2659d5b6455d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9285f59-8e1e-4440-ac86-2488c7cb11d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # InleidendeTekstHome
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73504e16-f45a-49a9-baf2-1a461a4b4aeb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02450193-808b-42e8-b4cd-9a0991eb8258 # Titel H2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af0198f9-40dd-4c08-9608-66990acd2e03
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1944228b-667b-4679-a9a7-5cd61ba6363b # Titel H2.2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d48a8852-c3e6-454c-92b5-dc5c780bbe9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d1070e7-0af4-4cdd-85d3-91155db1b7f5 # Titel H2.3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db20ceef-7e17-4f29-9259-c9d1abd4b8e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 490c2259-3301-4bae-b894-f9e0f5fb5dd4
        userCondition: null
handle: overOns
hasTitleField: true
icon: address-card
name: 'Over ons'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
