color: null
fieldLayouts:
  ef0f4fa9-071f-4458-a34e-70edf7bf8a98:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5740900a-a187-492e-a875-0604063539b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea72abe5-bea8-4ae7-9a59-db81d2b10f9a # Titel h1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c218e80a-35d8-4fc0-b212-526588bf212e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02450193-808b-42e8-b4cd-9a0991eb8258 # Titel H2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dd16c56-650f-4444-b4c0-0b7e73355101
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # uitgebreide tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a043abb-9870-4609-91ee-09efadcd82af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1944228b-667b-4679-a9a7-5cd61ba6363b # Titel H2.2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af5b3b82-0a03-4cac-a6d1-054bebbf55af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7108a5e2-c2f3-4d7b-a353-7b9639603cda # Titel H3.1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 523b81a7-624c-47f7-ac9a-7571b45d0e90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17a88137-bc43-46c0-873c-2075f6999aee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f11d615-c555-4dab-ba67-cb8cccb52533
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f91e36f4-9384-45d5-b776-dd455ec19ade # Uitleg1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0e2eb51-d438-4bd0-82bb-15d8baa7284a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c0dc2c9-285c-45aa-887a-c887ea0e4c0d # Titel H3.2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fa59126-40a5-4b75-bce1-e447589332b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 23162187-50bf-4930-b65c-16f4631c8527 # Uitleg 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bab8b5a1-466b-4cf8-86a9-48acf42bd10d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf8f250d-e4d1-4d7d-9b2d-7715bf489fc9 # Foto 3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 859c045f-5bbc-41ac-a786-74231889a2d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 047f311b-5a9b-4f2a-83e5-bb93db79c152 # Foto 4
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29e0eef0-f80c-4b2d-9981-12bf106c0b21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 532c63e0-e8c9-43e6-a365-064f3559f2c4 # Foto 5
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f1f3587-dd18-410e-814f-42a48296c332
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f7d84687-b238-45e2-b016-23db3b7c1a0e
        userCondition: null
handle: prijzen
hasTitleField: true
icon: memo
name: Prijzen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
