color: blue
fieldLayouts:
  125b7959-d141-4398-9bf1-512cffc279a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2d968edf-0ba3-48b6-9939-739d07495fce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cc07e5fd-bf6d-4c12-971b-1b386c10f883 # Home Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 177a974f-0f75-4d02-bf7b-cf347038f106
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea72abe5-bea8-4ae7-9a59-db81d2b10f9a # Titel h1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69b79c12-4d01-47f0-882a-51ba60edff16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02450193-808b-42e8-b4cd-9a0991eb8258 # Titel H2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 440151a1-67c4-4883-9a4b-1bf1ba8527e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbdf9d66-e771-4ea6-b065-36d46f769535 # InleidendeTekstHome
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 459f078f-c79d-484b-815d-8c6895f4cbd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c0cd35b-1aba-46c8-b16a-d98f0be224f9 # Foto1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1d84f82-991f-41d0-b405-fc79f279332e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 35b61dda-4599-41ec-971a-683a1878b7d6 # Foto 2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78713701-47f8-451f-8b8c-ec3d446ec06c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf8f250d-e4d1-4d7d-9b2d-7715bf489fc9 # Foto 3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7aec2808-5e14-4e65-b3dc-360c31984c15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1944228b-667b-4679-a9a7-5cd61ba6363b # Titel H2.2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9725ee13-2adb-477f-949c-91f156959cdb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7108a5e2-c2f3-4d7b-a353-7b9639603cda # Titel H3.1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9961fe28-f50d-4513-be08-3efbb882287e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c0dc2c9-285c-45aa-887a-c887ea0e4c0d # Titel H3.2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e2984a8-f02d-4b60-9061-3cc75ef3a25e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 486688b8-6ea0-4455-96eb-adb504204342 # Titel H3.3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76f98f09-fa71-42f2-8cd7-4ac4c9d0d17a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 10a43b4a-2950-4a68-9db6-9ead8ae73b03 # achtergrond initiatie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f59b8263-a69a-4556-9cf0-41507fe55a35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cc0e134-280b-4ce9-a93f-34904f77d1de # achtergrond clubduiken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45be099b-35f5-4b0b-a129-398685a2ccb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d6cd970f-8faf-48e1-aac2-6fcd8950dcf3 # achtergrond trainingen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3fd3d7a-0e82-424e-86e4-25a7e9258f78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d1070e7-0af4-4cdd-85d3-91155db1b7f5 # Titel H2.3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 266a74f1-0bde-4857-b548-e51b1206e160
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47a8103a-d6e1-4e9c-90b0-fd478802db4d
        userCondition: null
handle: startpagina
hasTitleField: true
icon: house
name: Startpagina
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
