altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fa94bbda-cce7-499c-b84c-00414a809008:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: dd2de7dc-d3e2-4665-ab3a-2238df225378
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b4840676-03fa-4c17-a9d1-07748fe1a5a6
        userCondition: null
fs: files
handle: bestuur
name: Bestuur
sortOrder: 2
subpath: '@webroot\assets\bestuur'
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
