altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  651091a6-5e6d-40a3-9bc1-0fc9c1cd9137:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 229e5125-4bcb-45dd-98fc-c008091f5179
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 73c9ca95-b2e1-4608-aa45-60732a67062f
        userCondition: null
fs: files
handle: boetiek
name: Boetiek
sortOrder: 5
subpath: boetiek
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
