altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  36105100-3740-4567-b42c-3b33ff1c4d28:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 57b31ccb-05cf-43cd-8fca-75f5612d6bb6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cf35fd24-383d-44f3-8325-df7486e6847f
        userCondition: null
fs: files
handle: logos
name: 'Logo''s'
sortOrder: 3
subpath: logos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
