columnSuffix: null
handle: categorie
instructions: null
name: producten-categorie
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  source: 'group:6145837d-f147-4a50-a650-289de5248d9a' # producten-categorie
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
