columnSuffix: null
handle: googleMapsLink
instructions: null
name: 'Google Maps link'
searchable: false
settings:
  maxLength: 500
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
