columnSuffix: null
handle: knopLinktNaar
instructions: null
name: 'knop linkt naar'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
