columnSuffix: null
handle: maat
instructions: null
name: Maat
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - XS
        -
          - value
          - xs
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - S
        -
          - value
          - s
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - M
        -
          - value
          - m
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - L
        -
          - value
          - l
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - XL
        -
          - value
          - xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - XXL
        -
          - value
          - xxl
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
