columnSuffix: null
handle: uitleg2
instructions: null
name: 'Uitleg 2'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: d912c11c-507e-49ef-b4b6-c5877d355fda # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
