defaultPlacement: end
enableVersioning: true
entryTypes:
  - 97764720-a98b-4ef7-ab8d-b580b2fbf962 # boetiek
handle: boetiek
maxAuthors: 1
name: Boetiek
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: boetiek.twig
    uriFormat: boetiek
type: single
