defaultPlacement: end
enableVersioning: true
entryTypes:
  - d10fa2a6-2fa0-4ca1-a7bf-856b57fd0d0c # Brevetten
handle: brevetten
maxAuthors: 1
name: Brevetten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: brevetten/_entry
    uriFormat: 'brevetten/{slug}'
type: channel
