defaultPlacement: end
enableVersioning: true
entryTypes:
  - eaa7e28f-4742-4c66-999b-b00a7ab41bcd # empty
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact
type: single
