defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2ca46e19-0e74-4d55-8020-73178a86907e # documenten
handle: documenten
maxAuthors: 1
name: Documenten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: _snippets\_documenten.twig
    uriFormat: 'documenten/{slug}'
structure:
  maxLevels: null
  uid: 4de14bad-d20c-4afc-b4c3-b4d835b2a351
type: structure
