defaultPlacement: end
enableVersioning: true
entryTypes:
  - 24270014-0a29-4a8a-9cd7-1bacac913949 # Duiken
  - d1809068-0b65-420d-a675-e40b84fe0109 # Duiksport
  - 050a6c8f-b201-4a7c-bf27-90550f2a81b1 # Prijzen
  - b56f921c-3a00-4fec-b19c-58f744660752 # Lessen
  - 2c4e8754-f3bf-4096-9ae3-9a11212c3654 # Duikplaatsen
  - f287c90d-2adb-4d28-b12d-dcd0d25fa64d # Duikplaatsen-indiv
handle: duiken
maxAuthors: 1
name: Duiken
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: duiken/_entry
    uriFormat: 'duiken/{slug}'
structure:
  maxLevels: null
  uid: 3345f940-7192-471d-bf93-a8a3f705f15a
type: structure
