defaultPlacement: end
enableVersioning: true
entryTypes:
  - d1809068-0b65-420d-a675-e40b84fe0109 # Duiksport
handle: duiksport
maxAuthors: 1
name: Duiksport
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: duiksport.twig
    uriFormat: duiksport
type: single
