defaultPlacement: end
enableVersioning: true
entryTypes:
  - 24270014-0a29-4a8a-9cd7-1bacac913949 # Duiken
handle: duiken
maxAuthors: 1
name: Duiken
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: duiken.twig
    uriFormat: duiken
type: single
