defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2a3eea25-77ba-47cc-85b0-a1920e038b0d # Federaties
handle: federaties
maxAuthors: 1
name: Federaties
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: _snippets\_federaties.twig
    uriFormat: 'federaties/{slug}'
structure:
  maxLevels: null
  uid: 99227c48-801c-41bd-bf51-630d49afbc3a
type: structure
