defaultPlacement: end
enableVersioning: true
entryTypes:
  - c865d06d-8839-4496-9b92-2940367417d2 # galerij
handle: galerij
maxAuthors: 1
name: galerij
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: galerij.twig
    uriFormat: galerij
type: single
