defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7e711192-549e-49af-aeaa-02f1edd3fadc # ICE
handle: ice
maxAuthors: 1
name: ICE
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: ice/_entry
    uriFormat: 'ice/{slug}'
type: channel
