defaultPlacement: end
enableVersioning: true
entryTypes:
  - bc0bc75a-81c8-46b2-b5ec-9aef29a6b48e # kalender
handle: kalender
maxAuthors: 1
name: Kalender
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: kalender.twig
    uriFormat: kalender
type: single
