defaultPlacement: end
enableVersioning: true
entryTypes:
  - cfeb32e3-62ea-485e-a0c9-e446aa903e3f # Knop
handle: knoppen
maxAuthors: 1
name: knoppen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: knoppen/_entry
    uriFormat: 'knoppen/{slug}'
type: channel
