defaultPlacement: end
enableVersioning: true
entryTypes:
  - dadb8ae5-9828-42c5-b632-584450769587 # Leden
handle: leden
maxAuthors: 1
name: Leden
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: leden.twig
    uriFormat: leden
type: single
