defaultPlacement: end
enableVersioning: true
entryTypes:
  - b56f921c-3a00-4fec-b19c-58f744660752 # Lessen
handle: lessen
maxAuthors: 1
name: Lessen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: lessen.twig
    uriFormat: lessen
type: single
