defaultPlacement: end
enableVersioning: true
entryTypes:
  - 38526ff8-201f-4280-9758-4eafe67903af # Initiatie
handle: lessenInitiatie
maxAuthors: 1
name: 'Lessen initiatie'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: lessen-initiatie/_entry
    uriFormat: lessen-initiatie
type: single
