defaultPlacement: end
enableVersioning: true
entryTypes:
  - 11147af8-ba68-4687-889a-d191c60d47c7 # locaties
handle: locaties
maxAuthors: 1
name: Locaties
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: _snippets/_locaties.twig
    uriFormat: 'locaties/{slug}'
type: channel
