defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2e76eb1e-7c0d-401b-8a0a-13759e3c51b2 # Login
handle: login
maxAuthors: 1
name: login
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: login.twig
    uriFormat: login
type: single
