defaultPlacement: end
enableVersioning: true
entryTypes:
  - d00f9e93-2d15-43f4-8dcb-b6e87b13ba35 # Over ons
handle: overOns
maxAuthors: 1
name: 'Over ons'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: over-ons/_entry
    uriFormat: over-ons
type: single
