defaultPlacement: end
enableVersioning: true
entryTypes:
  - 050a6c8f-b201-4a7c-bf27-90550f2a81b1 # Prijzen
handle: prijzen
maxAuthors: 1
name: prijzen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: prijzen.twig
    uriFormat: prijzen
type: single
