defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7817d0be-7eec-4496-b32d-80a546b83654 # met 3 foto's
  - 750b8283-62c8-4f9f-bddd-a2f23039c1bd # met 2 foto's
  - 39b95000-0f70-40d4-a6c7-b721d6a0e2f1 # Met 1 foto
handle: watDoenWij
maxAuthors: 1
name: 'Wat doen wij?'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c967232c-866e-40c6-936d-7d06ff30cba0: # Duikclub Dolfijn
    enabledByDefault: true
    hasUrls: true
    template: wat-doen-wij/_entry
    uriFormat: 'wat-doen-wij/{slug}'
type: channel
